CREATE TABLE reports (
    id INTEGER PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES posts,
    reporter_id INTEGER NOT NULL REFERENCES users,
    reason TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read BOOL NOT NULL DEFAULT FALSE
);
